# Autogenerated wrapper script for resvg_jll for aarch64-linux-musl
export resvg

JLLWrappers.@generate_wrapper_header("resvg")
JLLWrappers.@declare_executable_product(resvg)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        resvg,
        "bin/resvg",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
