# Autogenerated wrapper script for resvg_jll for x86_64-w64-mingw32
export resvg

JLLWrappers.@generate_wrapper_header("resvg")
JLLWrappers.@declare_executable_product(resvg)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        resvg,
        "bin\\resvg.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
